<?php

namespace Mediashare\PartnerBundle\Entity;
use Mediashare\AdminBundle\Entity\PagerRepository;


/**
 * PartnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerRepository extends PagerRepository
{
}
